name: 'Deploy coverage report results'
description: 'A GitHub Action for viewing the results of Parasoft coverage report on GitHub.'
author: 'Parasoft'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  report:
    description: 'Path or minimatch pattern to locate Parasoft coverage report XML files. If using a relative path, it is relative to the GitHub workspace directory. e.g. **/coverage.xml'
    required: true
  parasoftToolOrJavaRootPath:
    description: 'Root path to the Parasoft tool or Java installation required to locate the Java environment for report processing. If not specified, the GitHub Action will attempt to use the path from the JAVA_HOME environment variable.'
    required: false
runs:
  using: node20
  main: 'dist/index.js'